### ISSUE TITLE
container-interop: wrong composer dependency

### ISSUE THREAD

**Issue by solverat** [mnapoli/Invoker#14]
In your [composer.json](https://github.com/PHP-DI/Invoker/blob/master/composer.json#L19):
```json
 "require": {
        "container-interop/container-interop": "~1.1"
    },
```

Because of this, my system just updated `container-interop` from `1.1.0` to `1.2.0`. This may ship some breaking changes because of a minor update. instead of defining `~1.1` it's better to set a `~1.1.0` dependency, or am i wrong?

**Comment by jdreesen** [comment]
According to SemVer minor updates are **not** allowed to contain breaking changes.

The change between v1.1 and v1.2 ([which also deprecates the package](https://github.com/container-interop/container-interop#deprecation-warning)) is just that it now extends the officially accepted PSR-11 (which should be used instead) and thus allows an easier upgrade path.

Also, see: https://github.com/container-interop/container-interop/pull/91#pullrequestreview-21808979

**Comment by solverat** [comment]
True, this upgrade does not break anything. I was just concerned that it may break something in the future. :) Thanks anyway for your investigation!

**Comment by mnapoli** [comment]
:+1: thanks @jdreesen
