### ISSUE TITLE
String classname as a callable ?

### ISSUE THREAD

**Issue by ncou** [mnapoli/Invoker#23]
Hi,

Nice piece of code. Just a quick question. Looking at the code i can't understand the test on the class name line 47. I think the classname will not be considered a callable (even if there is an __invoke function) but as string.

https://github.com/PHP-DI/Invoker/blob/master/src/Reflection/CallableReflection.php#L47

What am i missing ?

**Comment by mnapoli** [comment]
Hi, I'm not sure I understand your question, could you clarify?

**Comment by ncou** [comment]
Sorry i will try to clarify (even if my english is poor).

As i understand, the CallableReflection->create($callable) function expect the parameter $callable to be a callable (and this callable will be used later for the function "call_user_func_array()").

Line 47 the check to do a reflection is : $callable should be a string, a valid classname with an existing method "__invoke".
In this case the piece of code will pass the check :

```php
$callable = Foobar::class;

class FooBar {
	public function __invoke() {
		return 'FooBar';
	}
}
```

But later when you will do the call_user_func_array($callable, []) it shouldn't work because $callable is not a valid callable (because the class is not instanciated).

But perhaps i am in the wrong (i only looked at the code).

**Comment by prisis** [comment]
When later and where?

Later you need to call call_user_func_array([FooBar::class, '__invoke'], [])

**Comment by ncou** [comment]
"Later and where" is in the Invoker class, i was not saying you call it manually => line 82  https://github.com/PHP-DI/Invoker/blob/master/src/Invoker.php#L82

**Comment by ncou** [comment]
What i am thinking is the test in the callablereflection for a classname with invoke method is useless.
In the invoker class line 56 the is_callable check will throw and exception if $callable is only a string classname.

**Comment by prisis** [comment]
this line https://github.com/PHP-DI/Invoker/blob/master/src/Invoker.php#L53 is resolving the string class with __invoke only if a container is provided else a exception is happening on line https://github.com/PHP-DI/Invoker/blob/master/src/Invoker.php#L57

And maybe you will use the CallableReflection.php outside the call function

**Comment by mnapoli** [comment]
👍  that is exactly that.

The concept of "callable" in the package has two sides:

- a real PHP callable
- a "magic" callable that can be resolved from the container (to become a real PHP callable)

**Comment by ncou** [comment]
Thanks it's more clear.
