### ISSUE TITLE
factory: optional parameter becomes factorydefinition

### ISSUE THREAD

**Issue by jworreth** [mnapoli/Invoker#24]
Copy of issue [#628](https://github.com/PHP-DI/PHP-DI/issues/628) from PHP-DI/PHP-DI

**Comment by jworreth** [comment]
Should be resolved with PR #25

**Comment by mnapoli** [comment]
Following https://github.com/PHP-DI/PHP-DI/issues/628#issuecomment-633238067 I have pushed a test that covers this behavior.

It is actually "logical", and not something we want to change. See https://github.com/PHP-DI/Invoker/blob/3357ef3d555d2f82d6df68f79e3d88e8ccaea6d8/tests/InvokerTest.php#L289-L295 for more details.
