### ISSUE TITLE
2.1.0 should have been a major release

### ISSUE THREAD

**Issue by hypeJunction** [mnapoli/Invoker#27]
Gusy, you have bumped PHP version requirement to 5.3 and tagged the release as a feature release. It is a breaking change for people that run PHP 7.2, IMO should have been 3.0.0, not 2.1.0.

**Comment by mnapoli** [comment]
This isn't a BC break. There is a lot of documentation around this online, I invite you to read about it. This is something done by packages all over the place, and definitely semver compatible.

The gist of it is: run the app locally + build your app for deployment with the same PHP version as production (or configure composer.json if you don't, that's also a possibility).
