### ISSUE TITLE
CallableReflection with invocable class name as parameter throws TypeError

### ISSUE THREAD

**Issue by sebastian84** [mnapoli/Invoker#31]
The following code example throws:

> TypeError: Argument 1 passed to Invoker\Reflection\CallableReflection::create() must be callable, string given.

```php
class Invokable
{
    public function __invoke() { }
}

\Invoker\Reflection\CallableReflection::create(Invokable::class);
```

The TypeError is caused by the _callable_ type hint added in version 2.2.0 to the _create_ method of the CallableReflection class. Without it the code runs without an error.

**Comment by mnapoli** [comment]
Hi!

I don't think there is an error here, but I may be wrong. `Invokable::class` is not a callable, and the Invoker should resolve that into an object (which _is_ callable) from the container before calling `CallableReflection`.

That made me discover that there is a piece of code in `CallableReflection` that is never called (the one you seemed to be using). Out of curiosity, this class is an internal class of the package, not supposed to be called directly. Do you use it directly in your codebase? Could you explain a bit more?

**Comment by sebastian84** [comment]
Hi!

Yes I am using the CallableReflection class directly. In my codebase I have an ExceptionListener class that gets a callable as constructor parameter but without the "callable" type hint. If an exception is thrown I am using the CallableReflection class to convert this callable parameter to a "true" callable to check if a parameter is present and has the same type as the thrown exception. If the parameter has the same type or there is no parameter, the callable is called otherwise not. Because the callable should not always beeing called I don't use the Invoker class here. I hope it is clear what I am doing in my code.

The code from the CallableReflection class that is used in my example is not covered by PHPUnit tests. (line 44)

**Comment by mnapoli** [comment]
OK I see. Unfortunately that seems out of the scope of the project :/ CallableReflection is an internal class, not really meant to be used outside.

I would suggest copying the previous version of the class into your project. To avoid any future confusion I'll tag this class as `@internal` and clean up the previously unused lines of code (or rather those unused in the Invoker itself).

Sorry for the trouble!

**Comment by sebastian84** [comment]
I totally understand that my use case is out of scope of the project. I will copy the previous version into my project.

Thank you for your support and the great work on the php-di container. I really enjoy using it.

**Comment by mnapoli** [comment]
Thank you!
