### ISSUE TITLE
NotCallableException without extra info when callable is valid and  __callStatic magic method used

### ISSUE THREAD

**Issue by defaultpage** [mnapoli/Invoker#38]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.3.0

#### Summary
If we use **valid callable** with `__callStatic` magic method instead of existing static method, then we get an error `is not a callable` without any extra info.

#### Expected behavior

Successfully execution or an error with a message 
`Xtreamwayz\PsrContainerMessenger\Container\TransportFactory::some.transport.example() is not a callable.  A __callStatic() method exists but magic methods are not supported.`

#### Current behavior

`Xtreamwayz\PsrContainerMessenger\Container\TransportFactory::some.transport.example() is not a callable.`
https://github.com/PHP-DI/Invoker/blob/5a46b9d1d41af98e7a50e6a6edeb3bb207b9d59f/src/Invoker.php#L49-L56
https://github.com/PHP-DI/Invoker/blob/5a46b9d1d41af98e7a50e6a6edeb3bb207b9d59f/src/Reflection/CallableReflection.php#L34-L36
https://github.com/PHP-DI/Invoker/blob/5a46b9d1d41af98e7a50e6a6edeb3bb207b9d59f/src/Exception/NotCallableException.php#L17-L20

#### How to reproduce

```php

namespace Xtreamwayz\PsrContainerMessenger\Container;

class TransportFactory {
    public static function __callStatic(string $dsn, array $arguments) {
        // return (new self($dsn))($arguments[0]);
    }
}
```

```php
$callableReflection = CallableReflection::create([TransportFactory::class, 'some.transport.example']);
```
or 

```php
$invoker->call([TransportFactory::class, 'some.transport.example']);
```

**Comment by artemmolotov** [comment]
Are there plans to support magical methods?
