### ISSUE TITLE
Debian packaging of this library

### ISSUE THREAD

**Issue by williamdes** [mnapoli/Invoker#47]
I did make up this description for the library: https://salsa.debian.org/php-team/pear/php-di-invoker/-/blob/debian/unstable/debian/control#L26

What do you think?

First line is the short description
and after is the long one

**Comment by mnapoli** [comment]
That looks great, thanks for sharing!

**Comment by williamdes** [comment]
> That looks great, thanks for sharing!

Cool, I will keep you updated on the packaging process
I will package php-di next

**Comment by williamdes** [comment]
[php-di](https://tracker.debian.org/pkg/php-di) is in Debian since one year now, the PHP 8.4 fixes are awaited to allow PHP 8.4 to enter Debian
