### ISSUE TITLE
Static method with arguments

### ISSUE THREAD

**Issue by alexandernst** [mnapoli/Invoker#6]
Is it possible to call a static method with arguments?

Like: 

```
$invoker->call('MyClass::myStaticMethod', array("foo" => 3, "bar" => 52));
```

**Comment by mnapoli** [comment]
Yes.

**Comment by alexandernst** [comment]
One more thing, is

```
$invoker->call('Foo\Bar\MyClass::myStaticMethod', array("foo" => 3, "bar" => 52));
```

possible too?

**Comment by mnapoli** [comment]
Could you please test? Or read the documentation?

**Comment by alexandernst** [comment]
The doc doesn't mention anything about calling namespaces classes, and I figured out I'd ask rather than setting up an entire demo (which would possibly crash and then I wouldn't know if it crashed because of my fault or because this is not supported, and I'd end up asking here).

**Comment by mnapoli** [comment]
So your time is more valuable than mine?

And the docs says: "Invoke any PHP callable". Both of your examples are straight PHP callables, so yes it works.
