### ISSUE TITLE
var_export on callable is not good on `[$object, 'method']` callables

### ISSUE THREAD

**Issue by ckressibucher** [mnapoli/Invoker#9]
in https://github.com/PHP-DI/Invoker/blob/master/src/CallableResolver.php#L45
`var_export` is used as message for the Exception. It's not good if the callable is `[$object, 'method']`, and the `$object` is complex, e.g. contains circular references.

**Comment by mnapoli** [comment]
Good catch, you are welcome to submit a pull request :)

**Comment by mnapoli** [comment]
I've released v1.3.1 that fixes this. Thanks
